### ISSUE TITLE
Does not work with google authenticator

### ISSUE THREAD

**Issue by kartoch** [matlink/gplay-cli#1]
Using strong authentication, I've the following error message:

    $ python gplay-cli.py -s runtastic
    server says: NeedsBrowser
    Traceback (most recent call last):
      File "gplay-cli.py", line 224, in <module>
        cli.search(list(),args.search_string,nb_results)
      File "gplay-cli.py", line 159, in search
        results = self.playstore_api.search(search_string, nb_results=nb_results).doc
    AttributeError: 'GPlaycli' object has no attribute 'playstore_api'

**Comment by matlink** [comment]
Alright, thanks for report, I'll check it soon ! :)

**Comment by kartoch** [comment]
Checking, seems related to `googleplay-api` which is quite unmaintained and not issues about strong authentication, I think switching to simple authentication for first authentication is the only solution at the present time...

**Comment by matlink** [comment]
It means you're using your own credentials ? The default ones aren't good for you or you simply wanna use yours ?

**Comment by kartoch** [comment]
Yes I'm using my owns. I will use the default to check if OK.

**Comment by flyinva** [comment]
Not better with default credentials

``` 
./gplaycli.py --update /srv/fdroid/repo/ --verbose --progress  --config /usr/local/gplaycli/credentials.conf
Cannot login to GooglePlay ( server says: NeedsBrowser )
```

**Comment by matlink** [comment]
I've updated creadentials.conf. Can you try again after having pulled 
the update ?

**Comment by flyinva** [comment]
It works !!

Merci beaucoup ;-p

**Comment by matlink** [comment]
To avoid you being impacted by dumbass kids which change the password of 
the account, make sure to use your google account and generate your 
AndroidID. It's explained at the end of the README.md file.
